### PR TITLE
Spanish translation corrections and additions 

### PR DESCRIPTION
**Pull request by UlisesAlexanderAM**
I made some work on the issue #533.

### CODE REVIEW

**Comment by chubin** [comment]
@UlisesAlexanderAM Thank you for your corrections. Funny enough, the Spanish translation is getting corrected most often :) For example, the "Nevada" translation is being added/reverted one a month :)

**Comment by UlisesAlexanderAM** [comment]
@chubin In that case we should make a discussion about that word or words in the same situation, to avoid added/reverted every time.

**Comment by chubin** [comment]
@UlisesAlexanderAM Can you please take a look at history of `es.txt`? You can find other options there

**Comment by UlisesAlexanderAM** [comment]
@chubin Ok, thanks for the feedback.

**Pull request merged**
