### PR TITLE
Added Interlingua translation

### PR DESCRIPTION
**Pull request by dustinkredmond**
Since we have Esperanto, I've added the translation for Interlingua (another auxillary language)

### CODE REVIEW

**Comment by chubin** [comment]
@dustinkredmond Thank you, and you missed two the most important files:

* https://github.com/chubin/wttr.in/blob/master/share/translations/de-help.txt
* https://github.com/chubin/wttr.in/blob/master/share/translations/de.txt

**Comment by dustinkredmond** [comment]
@chubin Whoops, sorry about that, I've added another commit with "ia.txt" and "ia-help.txt"

**Comment by chubin** [comment]
@dustinkredmond Merged, deployed! Please test.
It looks great

**Comment by dustinkredmond** [comment]
@chubin Tested and I agree. All looks great!

**Pull request merged**
