### PR TITLE
translations: add be

### PR DESCRIPTION
**Pull request by edogby**

### CODE REVIEW

**Comment by chubin** [comment]
Why have you closed it?

**Comment by chubin** [comment]
@edogby Is something wrong with the translation, or you've closed it for some other reason?

**Comment by chubin** [comment]
And could you please share with me the name that should be written in the /:translation file?

**Comment by edogby** [comment]
Translation is ok, I spent enough time. Just would like to recheck while it wasn't merged.
Name: Anton Zhavoronkov.

Thank you!

**Comment by chubin** [comment]
Sorry for not having merged it before, the only reason for that was that I had no enough time. Thank you very much for your contribution!

**Pull request merged**
