### PR TITLE
Additional Simplified Chinese translation

### PR DESCRIPTION
**Pull request by junhan-z**
Added simplified Chinese translation.

### CODE REVIEW

**Comment by gnowxilef** [comment]
takes care of https://github.com/chubin/wttr.in/issues/83

**Comment by junhan-z** [comment]
Ah, alright.

**Comment by gnowxilef** [comment]
you should keep this pr open. it still needs to be merged.

**Comment by chubin** [comment]
@gnowxilef Thank you for mentioning it. I somehow missed this PR, but there are still several things that have to be added for the Simplified Chinese translation

**Pull request merged**
