### PR TITLE
Plain text weather symbols

### PR DESCRIPTION
**Pull request by hejops**
This should address https://github.com/chubin/wttr.in/issues/270

### CODE REVIEW

**Comment by chubin** [comment]
Thank you! I mentioned it also in README.md.
It is deployed, can you please test it?

**Comment by hejops** [comment]
Yes, it works:
```
curl -sL wttr.in/Munich?format="%C,+%t+(%x)"
Light rain and snow shower, rain and snow shower, +4°C (*/*)
```

**Comment by chubin** [comment]
Thank you @hejops 
BTW, if you like the project, feel free to contribute.
Here are some tickets that could be interesting for you:

https://github.com/chubin/wttr.in/labels/one-line

**Comment by hejops** [comment]
I'll have a look at what I can manage

**Pull request merged**
