### PR TITLE
nn translations

### PR DESCRIPTION
**Pull request by unhammer**
I couldn't find the other strings – are they not translatable?

### CODE REVIEW

**Comment by chubin** [comment]
Thank you very much for the translation! Yes, they are translatable, but they are not yet committed. If you are willing to help, I can send you the file with the text to be translated. There are about 30 terms to translate.

**Comment by unhammer** [comment]
yes please :)

**Comment by chubin** [comment]
Here is it: http://igor.chub.in/wttr.in-nn.txt
Thank you very much for your help!

**Comment by unhammer** [comment]
[wttr.in-nn.txt](https://github.com/chubin/wttr.in/files/870619/wttr.in-nn.txt)
could probably do with a check by a meteorologist :)

**Comment by chubin** [comment]
Could you please checkin you translation with your credentials?
I've added the translation to the server installation, but not in the repository on github,
because I think it's better when the files belong their authors.

[nn.txt](https://github.com/chubin/wttr.in/files/883250/nn.txt)

And please check you translation, how it looks like:

http://wttr.in/?lang=nn

What do you think?

**Comment by unhammer** [comment]
Looks good :-) Checked in here: https://github.com/chubin/wttr.in/pull/91 (if that's what you meant)

**Comment by chubin** [comment]
Perfect! If there will be some new weather conditions that are not yet translated, I will write here about them.
I added your name here (if you don't mind):

http://wttr.in/:translation

And what about Bokmål? Could you help with the translation may be? We still don't have it. I think there are not so many European languages that we don't support now and Bokmål is one of them

**Comment by unhammer** [comment]
Sure; may take a few days until I get round to it though

**Comment by chubin** [comment]
Not a problem. Thank you very much!

**Pull request merged**
