### PR TITLE
Translate `Rain` according to #324

### PR DESCRIPTION
**Pull request by iago-lito**
I'll try not to close the PR too early this time ;)

### CODE REVIEW

**Comment by chubin** [comment]
Thank you for the PR; I will deploy it live today

**Comment by chubin** [comment]
Done

**Comment by iago-lito** [comment]
Great. I've found [two](https://github.com/chubin/wttr.in/pull/365/commits/71a8ce7db4e57039b94cc5e490b319d23df1ab17) [more](https://github.com/chubin/wttr.in/pull/365/commits/90228d1d883e4d73b2494818b9381ac5a2581bf9) missing translations. Is there a list of all such items so I can translate them all at once?

**Comment by chubin** [comment]
Unfortunately not, there is no list of all possible weather conditions that the API returns. But what we can do, we can save all entries that could not be translated, and then after some time we have all of them

**Comment by iago-lito** [comment]
Good idea. I'll keep on adding the few ones I see sometimes. And feel free to tell me when you have a list :)

**Pull request merged**
