### PR TITLE
Hungarian help text

### PR DESCRIPTION
**Pull request by mpetruska**
* [x] add Hungarian help text
* [x] ready for review/merge

### CODE REVIEW

**Comment by mpetruska** [comment]
@chubin I'd like a review for this one, please. :)

**Comment by chubin** [comment]
@mpetruska Now it is just perfect! Thank you very much

**Comment by mpetruska** [comment]
@chubin Thanks, please feel free to contact me, for any new texts to translate to Hungarian. :smile:

**Comment by chubin** [comment]
@mpetruska Thank you Mark! Probably we will need your help soon indeed

**Pull request merged**
