### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by woodjosh256**
This pull request configures this repository to be run on Repl.it.      It adds a `.replit` configuration file and a Repl.it badge to the `README`.
     You can read more about running repos on Repl.it [here](https://docs.repl.it/repls/dot-replit), or view the Repl [here](https://repl.it/@joshwood/wttrin).

### CODE REVIEW

**Comment by chubin** [comment]
It is an interesting idea. Can you please give me a couples of examples of repositories with the repl.it badge + give more details, why it could be useful for the wttr.in users and lovers?

**Comment by woodjosh256** [comment]
I think the primary benefit of using a repl.it badge would be that it allows prospective users to test wttr.in directly from the browser without installation. The badge is quite new (came out yesterday, I believe) so there aren't a ton of repositories with the repl.it badge yet.
Here are a couple, though:
https://github.com/frostming/legit
https://github.com/unknownblueguy6/MineSweeper
https://github.com/jarun/ddgr

Also, yes I agree opening with `print(requests.get("http://wttr.in/?n2").text)` would be more relevant and better demonstrate the wttr.in's capabilities.

**Comment by chubin** [comment]
@woodjosh256 Sorry for the long time it took for the answer.

I played a little bit with the repl.it, and it seems to me that it could be pretty interesting,
as some extended platforms to experiment with wttr.in.

Do you know how it could be possible to add/run several commands
in the terminal of repl.it? In the right section?

It would be great to show there several different output formats (normal, v2, one-line).

**Comment by chubin** [comment]
I still didn't find a good usecase for it, maybe I will find it later. If you have new ideas/arguments,please feel free to comment/reopen it

**Pull request closed without merging**
