### PR TITLE
Added Norwegian translation

### PR DESCRIPTION
**Pull request by fredrikfjeld**

### CODE REVIEW

**Comment by chubin** [comment]
Hi @fredrikfjeld !

Sorry for the delay. I was on a vacation, but I'm back now. So we will make your beautiful translation public. 

Can you please answer on this question:

What location should I use to announce the new (Norwegian) translation? What is the most emblematic Norwegian place? Bodø? Trondheim? Tromsø? Hammerfest?  I would chose something that will make all Norwegians who'll read my twitter feel themselves happy. What wo you suggest? (example: for Catalonian: https://twitter.com/igor_chubin/status/874186824205324288 … )

**Comment by fredrikfjeld** [comment]
I hope you had a wonderful vacation!

I think Lofoten is one of the most stunning regions in Norway. This CC licensed photo captures it beautifully: https://pixabay.com/en/dawn-lofoten-boats-cabins-sky-1018660/

I think "Ville, vakre Lofoten!" is nice. It translates to "The wild and beautifull Lofoten!"

This is a region, though. If you want a more iconic single location the pulpit rock (Preikestolen) is a good fit, accompanied by the text "Preikestolen er spektakulær!" - "The pulpit rock is spectacular!".

The Holmenkollen ski jump in the capital Oslo is also very iconic. You could use my photo of it if you like: https://www.flickr.com/photos/fredrikf/15409711812/

**Comment by chubin** [comment]
Hi @fredrikfjeld !

Our Norwegian is finally online.

http://nb.wttr.in/

Please check my translations of the rest: "weather report", morning, noon, evening, night, and the dates. I hope, everything is ok, but I would like to get your approval.

As I said, I want to announce the translation in twitter.
I like the photo you've sent me (the one of Lofoten).

What do you think, if I use this verse in the announce:

Se oftere mot nord.
Gå mot vinden,
du får rødere kinn.
Finn den ulendte stien. Hold den.
Den er kortere. Nord er best.
Vinterens flammehimmel,
sommernattens solmirakel.
Gå mot vinden, Klyv berg.
Se mot Nord. Oftere.
Det er langt dette landet.
Det meste er nord.

I like it (at least its German translation), but I don't know which feelings it will induce in Norwegian souls (when read in this context). Should I post it or better to post only the short version "Ville, vakre Lofoten!"?

And thank you very much for the translation!
(I've noticed, that we've forgotten to translate /:help It's ok, becasue it is translated only into German, French and Russian, but not into the rest 50 languages, but if you have 10 minutes for this translation, it would be really great)

Tomorrow we will do the announce (if you answer me today, and we decide what we will write in the post)

**Comment by fredrikfjeld** [comment]
Beautifull poem you have selected! I think it's a great fit, especially with the picture from Lofoten.

I just pushed a translated /:help. Your translations of dates etc. looks goood!

**Comment by chubin** [comment]
Do you have a twitter account? (to mention it in the announce)

**Comment by chubin** [comment]
I've uploaded Norwegian help file; it looks very nice:

curl nb.wttr.in/:help

**Comment by fredrikfjeld** [comment]
Nice! My twitter account is @ffredrik.

**Pull request merged**
