### PR TITLE
Develop core repo update

### PR DESCRIPTION
**Pull request by Davoy**
These changes removes absolute paths for dependencies in order to have a more dynamic installation process. Some configuration files have been added with trial API keys for testing and additional required data.

Also resolved legacy code in wttr.py when calling the `wego` terminal command, it was being supplied invalid/deprecated flags. Flags have been updated or removed.

Lastly, geo-proxy.py cache had no check if the cache directory exists before writing, so I added validation on the directory to be created if not already present.

### CODE REVIEW

**Comment by chubin** [comment]
@Davoy why have you closed the pull-request? You don't want it to be merged?

**Comment by Davoy** [comment]
I am participating in CodeLabs Internship and our groups mentor selected wttr.in to look at and replicate or extend. We decided to extend it and had to work out some initial setup issues, but when I went to submit the changes to the groups repo I accidentally sent the PR to you.

My mentor advised that the goal is to submit a PR for the changes/enhancements by the end of the program, so you should be seeing a PR(s) here in the next 2 weeks.

While I have you, thanks for the application, though you may not have intended it to be an educational experience, I have learned a lot from this app and getting it to run. This has been a great application for this internship program!

**Comment by chubin** [comment]
@Davoy Very well!
Already asked about the progress in some other issue, but will ask it also here :)
Please don't wonder why suddenly there is some much attention and activity:
I've got a little bit more time for the project, and so I try to go through all open questions,
and see where I could help.

So I'm afraid that nothing came out of your initiative/project, and it is very pity, because
the things that you planned sounded very interesting and promising, and potentially useful
for the community. So there is a little change of recovery of the project and I could somehow help,
let me know

**Comment by Davoy** [comment]
@chubin my apologizes for the delayed PR submission, after the internship program ended, work life became very busy. We had many plans to enhance the existing wttr.in application, however there were too many issues when installing/configuring the application locally, so I mainly made some changes to the way the Dockerfile runs, updated some dependencies, and populated the README detailing a bit more on how to set up the project locally. 

I was the only member to add an enhancement, but due to helping the other team members, I was not able to finalize my piece, which was converting the weather data into an ASCII map to display on the terminal. This piece will not be part of the PR.

I will get a new PR set up with the work mentioned above, with the exception of my enhancement, at least for now.

**Pull request closed without merging**
