### PR TITLE
Update de.txt

### PR DESCRIPTION
**Pull request by Blueforcer**
add "Shower in vicinity" translation

### CODE REVIEW

**Comment by chubin** [comment]
Vielen Dank!

Wir haben eigentlich mehr "missing translations" in Deutsch; ich post sie mal alle hier,
und dann können wir sie gemeinsam übersetzen

**Comment by chubin** [comment]
```
drizzle and rain
drizzle with thunderstorm
dust storm
fog in vicinity
freezing drizzle and rain
freezing mist
freezing rain
freezing rain and snow
freezing unknown precipitation
hail shower
hail with thunderstorm
haze
heavy blowing snow
heavy drizzle
heavy drizzle and rain
heavy rain and hail with thunderstorm
heavy rain and small hail/snow pallets shower
heavy rain and small hail/snow pallets with thunderstorm
heavy rain and snow and small hail/snow pallets with thunderstorm
heavy rain and snow shower
heavy rain shower
heavy rain with thunderstorm
heavy snow shower
ice pallets
light blowing snow
light drizzle and fog
light drizzle and rain and snow
light drizzle and rain shower
light drizzle and rain with thunderstorm
light drizzle and snow
light drizzle with thunderstorm
light freezing drizzle
light freezing drizzle and rain
light freezing fog
light freezing rain and snow
light freezing unknown precipitation
light ice crystals
light ice pallets
light rain and ice pallets
light rain and mist
light rain and small hail/snow pallets shower
light rain and small hail/snow pallets with thunderstorm
light rain and snow
light rain and snow shower
light rain with thunderstorm
light shower
light showers of ice pellets
light small hail/snow pallets shower
light snow and ice pallets
light snow and small hail/snow pallets shower
light snow grains
light snow shower
light snow with thunderstorm
light thunderstorm
light unknown precipitation
light unknown precipitation shower
lilight rain and snow
low drifting sand
parftial fog
rain and hail with thunderstorm
rain and small hail/snow pallets shower
rain and small hail/snow pallets with thunderstorm
rain and snow
rain and snow shower
rain and snow with thunderstorm
rain in vicinity
rain with thunderstorm
sand
shallow fog
shallow mist
shower in vicinity
small hail/snow pallets
small hail/snow pallets shower
small hail/snow pallets with thunderstorm
smoke
snow and ice pallets
snow grains
snow shower
snow with thunderstorm
squalls
thunderstorm
thunderstorm in vicinity
unknown precipitation
volcanic ash
volcanic ash in vicinity
widespread dust
```

**Comment by chubin** [comment]
Maybe we should run the through google translate, to save some time... Because the list is pretty big, it will cost us a lot of time to translate it

**Comment by MAGICCC** [comment]
Weird I thought I did them all :D
Currently on vacation so either you can some sort of translator or wait for some native speakers.

Btw, ever thought if using Weblate or something like that for translating?

**Comment by chubin** [comment]
Yes, we did them all indeed, but there are some new ones :) volcanic ash for example :)
Anyway, I can translate them, and you can verify my translation after that.

I didn't use weblate before; you think it could help us?

**Comment by MAGICCC** [comment]
I use Weblate for one project. But I am not sure if it can handle the current file format

**Pull request merged**
