### PR TITLE
Create te.txt

### PR DESCRIPTION
**Pull request by pavansrinivasmamidala**

### CODE REVIEW

**Comment by chubin** [comment]
Thank you very much!
And the last question: what terminal do you usually use?

**Comment by pavansrinivasmamidala** [comment]
bash

**Comment by chubin** [comment]
I mean terminal (terminal emulator), not shell

-- 
Igor Chubin

**Comment by pavansrinivasmamidala** [comment]
I didnt understand u mean linux terminal??

**Comment by pavansrinivasmamidala** [comment]
I use manjaro

**Comment by chubin** [comment]
Is this script displayed correctly in this terminal for you?
Or do you have some problems with displaying it?

**Comment by pavansrinivasmamidala** [comment]
I don't have any problem displaying it..
It works fine but how can I check if it works in telugu or not?

**Pull request merged**
