### PR TITLE
Add full PL translation

### PR DESCRIPTION
**Pull request by wojtuch**

### CODE REVIEW

**Comment by wojtuch** [comment]
hi @chubin, I've created this PR some time ago, do you need anything else from my side in order to have it merged?

**Comment by chubin** [comment]
I'm sorry @wojtuch I've missed it. Thank you very much for pinging me.
The update is not live though, but it is already in the tree.
Could you give me your name and you twitter id (if you have any) for the /:translation page?

**Comment by wojtuch** [comment]
no problem!
please put Wojtek Łukasiewicz to the /:translation page. I'm not an avid twitter user so we can skip it. thanks!

**Comment by wojtuch** [comment]
happy to contribute!

**Pull request merged**
